name: Aula de GCS (PUC CAMPINAS)

on: [fork, push]

defaults:
  run:
    shell: bash
      # working-directory:

jobs: 
  primeiro: 
    runs-on: ubuntu-latest
    name: Primeiro Job escrito
    steps: 
      - name: Mostrar rodando
        run: echo "teste"
    
  segundo: 
    runs-on: windows-latest
    name: Segundo
    steps: 
      - name: Criando Variáveis de Ambiente
        env: 
          VAR1: Isto é
          VAR2: GitHub Actions
        run: echo $VAR1 $VAR2
